subugoe_counter_homepage:
    path:     /r5
    defaults: { _controller: SubugoeCounterBundle:SUSHI:index }

subugoe_counter_GetReport:
    path:     /r5/reports
    methods:   "GET"
    defaults: { _controller: SubugoeCounterBundle:SUSHI:reports }

subugoe_counter_pr1:
    path:     /r5/pr1
    methods:   "GET"
    defaults: { _controller: SubugoeCounterBundle:SUSHI:platformReport1 }

subugoe_counter_dr1:
    path:     /r5/dr1
    methods:   "GET"
    defaults: { _controller: SubugoeCounterBundle:SUSHI:databaseReport1 }