services:
  report_service:
    class: Subugoe\CounterBundle\Service\ReportService
    arguments: ["@doctrine", "@request_stack", "@service_container", "@solarium.client"]

  tracking.action_listener:
    class: Subugoe\CounterBundle\EventListener\PiwikTrackingListener
    arguments: ["@report_service", "@service_container"]
    tags:
        - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }